//@@@@@@@@@@@@@@@@ PROYECTO Brandom-Adoney
package view.administracion.acceso;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * González Olivares Brandon - Tejera Santana Adoney
 */
public class AdministracionGestionPasswordView extends javax.swing.JFrame {

    

    /**
     * Creates new form AdministracionInicioSesionView
     */
    public AdministracionGestionPasswordView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lbContraseñaactual = new javax.swing.JLabel();
        lblNuevacontraseña = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblRepetircontraseña = new javax.swing.JLabel();
        lblIncorrecto = new javax.swing.JLabel();
        lblNocoincide = new javax.swing.JLabel();
        fieldContraeñaactual = new javax.swing.JPasswordField();
        fieldNuevacontraseña = new javax.swing.JPasswordField();
        fieldRepetircontraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("Cambiar Contraseña");

        lbContraseñaactual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbContraseñaactual.setText("Contraseña Actual:");

        lblNuevacontraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNuevacontraseña.setText("Nueva Contraseña:");

        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblRepetircontraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRepetircontraseña.setText("Repetir Contraseña:");

        lblIncorrecto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIncorrecto.setForeground(new java.awt.Color(255, 10, 10));
        lblIncorrecto.setText("La contraseña actual no es correcta");

        lblNocoincide.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNocoincide.setForeground(new java.awt.Color(255, 10, 10));
        lblNocoincide.setText("La contraseña repetida no coincide");

        fieldRepetircontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRepetircontraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblRepetircontraseña)
                        .addComponent(fieldRepetircontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fieldContraeñaactual, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbContraseñaactual)
                        .addComponent(fieldNuevacontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNuevacontraseña))
                    .addComponent(lblNocoincide)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancelar))
                        .addComponent(lblIncorrecto)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(37, 37, 37)
                .addComponent(lbContraseñaactual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldContraeñaactual, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(lblNuevacontraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldNuevacontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRepetircontraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldRepetircontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIncorrecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNocoincide)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void fieldRepetircontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRepetircontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRepetircontraseñaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPasswordField fieldContraeñaactual;
    private javax.swing.JPasswordField fieldNuevacontraseña;
    private javax.swing.JPasswordField fieldRepetircontraseña;
    private javax.swing.JLabel lbContraseñaactual;
    private javax.swing.JLabel lblIncorrecto;
    private javax.swing.JLabel lblNocoincide;
    private javax.swing.JLabel lblNuevacontraseña;
    private javax.swing.JLabel lblRepetircontraseña;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    public JButton getbtnAceptar() {
        return this.btnAceptar;
    }
    public JButton getbtnCancelar() {
        return this.btnCancelar;
    }

    /**
     * @return the fieldNuevaContraseña
     */
    public javax.swing.JPasswordField getFieldNuevaContraseña() {
        return fieldNuevacontraseña;
    }

    /**
     * @return the fieldRepetircontraseña
     */
    public javax.swing.JPasswordField getFieldRepetircontraseña() {
        return fieldRepetircontraseña;
    }

    /**
     * @return the fieldContraeñaactual
     */
    public javax.swing.JPasswordField getFieldContraeñaactual() {
        return fieldContraeñaactual;
    }

    public javax.swing.JLabel getLblIncorrecto() {
        return lblIncorrecto;
    }

    public javax.swing.JLabel getLblNocoincide() {
        return lblNocoincide;
    }

    /**
     * @return the lbContraseñaactual
     */
   
}
