/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.administracion.gestion;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AdoneyDAW
 */
public class AdministracionProdcutosView extends javax.swing.JFrame {

    /**
     * Creates new form AdministracionProdcutosView
     */
    
    private final String[] categoriasTableColumns = {"ID", "Nombre", "Precio", "Categoría"};
    private DefaultTableModel categoriasTableModel;
    
    public AdministracionProdcutosView() {
        String[][] temporalCategoriasTableData = {{"1", "Coca Cola", "1,8", "Refrescos"}, {"2", "Bocadillo de Lomo", "2", "Bocadillos"}, {"3", "Hamburguesa con queso", "5,5", "Menus"}};
        
        this.categoriasTableModel = new DefaultTableModel(temporalCategoriasTableData, this.categoriasTableColumns) {
            @Override
            public boolean isCellEditable(int r1, int r2) {
                return false;
            }
        };
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tCategorias = new javax.swing.JTable();
        btnEliminarseleccion = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblCrearproducto = new javax.swing.JLabel();
        fieldCrearproductonombre = new javax.swing.JTextField();
        btnCrearproducto = new javax.swing.JButton();
        lblEditarproducto = new javax.swing.JLabel();
        btnEditarProducto = new javax.swing.JButton();
        lblCategorias = new javax.swing.JLabel();
        lblCrearproductonombre = new javax.swing.JLabel();
        lblCrearproductoprecio = new javax.swing.JLabel();
        fieldCrearproductoprecio = new javax.swing.JSpinner();
        lblEditarproductonombre = new javax.swing.JLabel();
        lblEditarproductoprecio = new javax.swing.JLabel();
        fieldEditarproductoprecio = new javax.swing.JSpinner();
        fieldEditarproductonombre = new javax.swing.JTextField();
        comboCrearProducto = new javax.swing.JComboBox<>();
        comboEditarProducto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tCategorias.setModel(this.categoriasTableModel);
        jScrollPane1.setViewportView(tCategorias);

        btnEliminarseleccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnEliminarseleccion.setText("Eliminar Selección");

        btnAtras.setText("Atrás");

        lblCrearproducto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblCrearproducto.setText("Crear Producto");

        fieldCrearproductonombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCrearproductonombreActionPerformed(evt);
            }
        });

        btnCrearproducto.setText("Crear");

        lblEditarproducto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblEditarproducto.setText("Editar Producto");

        btnEditarProducto.setText("Modificar");

        lblCategorias.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblCategorias.setText("Categorías:");

        lblCrearproductonombre.setText("Nombre:");

        lblCrearproductoprecio.setText("Precio");

        lblEditarproductonombre.setText("Nombre:");

        lblEditarproductoprecio.setText("Precio");

        fieldEditarproductonombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEditarproductonombreActionPerformed(evt);
            }
        });

        comboCrearProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Refrescos", "bocadillos", "Menus" }));
        comboCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCrearProductoActionPerformed(evt);
            }
        });

        comboEditarProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Refrescos", "bocadillos", "Menus" }));
        comboEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEditarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldEditarproductonombre, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblEditarproductonombre)
                                .addGap(139, 139, 139)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEditarproductoprecio)
                            .addComponent(fieldEditarproductoprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblEditarproducto)
                    .addComponent(lblCrearproducto)
                    .addComponent(btnCrearproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldCrearproductonombre, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCrearproductonombre)
                                .addGap(139, 139, 139)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCrearproductoprecio)
                            .addComponent(fieldCrearproductoprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCrearProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboEditarProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategorias))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminarseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrearproducto)
                    .addComponent(lblCategorias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(btnAtras))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCrearproductonombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldCrearproductonombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldCrearproductoprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCrearproductoprecio)
                                .addGap(30, 30, 30)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(lblEditarproducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEditarproductonombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldEditarproductonombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldEditarproductoprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEditarproductoprecio)
                                .addGap(30, 30, 30)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCrearproductonombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCrearproductonombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCrearproductonombreActionPerformed

    private void fieldEditarproductonombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEditarproductonombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEditarproductonombreActionPerformed

    private void comboCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCrearProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCrearProductoActionPerformed

    private void comboEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEditarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEditarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracionProdcutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracionProdcutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracionProdcutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracionProdcutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracionProdcutosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCrearproducto;
    private javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnEliminarseleccion;
    private javax.swing.JComboBox<String> comboCrearProducto;
    private javax.swing.JComboBox<String> comboEditarProducto;
    private javax.swing.JTextField fieldCrearproductonombre;
    private javax.swing.JSpinner fieldCrearproductoprecio;
    private javax.swing.JTextField fieldEditarproductonombre;
    private javax.swing.JSpinner fieldEditarproductoprecio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategorias;
    private javax.swing.JLabel lblCrearproducto;
    private javax.swing.JLabel lblCrearproductonombre;
    private javax.swing.JLabel lblCrearproductoprecio;
    private javax.swing.JLabel lblEditarproducto;
    private javax.swing.JLabel lblEditarproductonombre;
    private javax.swing.JLabel lblEditarproductoprecio;
    private javax.swing.JTable tCategorias;
    // End of variables declaration//GEN-END:variables
}
