/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.pedidos;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AdoneyDAW
 */
public class PedidosProductosView extends javax.swing.JFrame {

    /**
     * Creates new form PedidosProductosView
     */
    
    private DefaultTableModel facturaTableModel;
    private final String[] facturaTableColumns = {"Producto", "Precio", "Unidades", "Subtotal"};
    
    public PedidosProductosView(DefaultTableModel tableModel,String[] categoriasButtonNames) {
        this.facturaTableModel = tableModel;
        
        initComponents();
    }
    
    public void addProductosButtons(String[] nombreProductos) {
        
    }
    
    public JButton getBtnAtras() {
        return this.btnAtras;
    }
    
    public JLabel getLblCategorias() {
        return this.lblCategorias;
    }
    
    public JLabel getLblProductos() {
        return this.lblProductos;
    }
    
    public JLabel getLblNoHayCategorias() {
        return this.lblNoHayCategorias;
    }
    
    public JLabel getLblNoHayProductos() {
        return this.lblNoHayProductos;
    }
    
    public JLabel getLblNoSeleccion() {
        return this.lblNoSeleccion;
    }
    
    public JLabel getLblNoGuardar() {
        
    }
    
    public JButton getBtnEliminarSeleccion() {
        return this.btnEliminarseleccion;
    }
    
    public JButton getBtnGuardar() {
        return this.btnGuardar;
    }
    
    public JScrollPane getScrollPane() {
        
    } 
    
    public JTable getTable() {
        return this.tFacturas;
    }
    
    public JPanel getCategoriaPanel() {
        
    }
    
    public JPanel getProductoPanel() {
        
    }
    
    public JButton[] getCategoriasButtons() {
        
    }
    
    public JButton[] getProductosButtons() {
        
    }
    
    public JLabel getLblTotal() {
        return this.lblTotal;
    }
    
    public JButton getBtnMas() {
        return this.btnFacturasSum;
    }
    
    public JButton getBtnMenos() {
        return this.btnFacturasRes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCategorias = new javax.swing.JLabel();
        lblProductos = new javax.swing.JLabel();
        btnCatHamburguesas = new javax.swing.JButton();
        btnProCocacola = new javax.swing.JButton();
        btnProCocacolazero = new javax.swing.JButton();
        btnProFantanaranja = new javax.swing.JButton();
        btnProMonster = new javax.swing.JButton();
        btnProRedbull = new javax.swing.JButton();
        btnProNestea = new javax.swing.JButton();
        lblFacturas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tFacturas = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnFacturasSum = new javax.swing.JButton();
        btnEliminarseleccion = new javax.swing.JButton();
        btnFacturasRes = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblNoHayCategorias = new javax.swing.JLabel();
        lblNoHayProductos = new javax.swing.JLabel();
        lblNoSeleccion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCategorias.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCategorias.setText("Categorías: ");
        lblCategorias.setToolTipText("");
        lblCategorias.setFocusable(false);
        lblCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCategorias.setName(""); // NOI18N

        lblProductos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblProductos.setText("Productos: ");
        lblProductos.setToolTipText("");
        lblProductos.setFocusable(false);
        lblProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblProductos.setName(""); // NOI18N

        btnCatHamburguesas.setText("Hamburguesas");
        btnCatHamburguesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatHamburguesasActionPerformed(evt);
            }
        });

        btnProCocacola.setText("Cocacola");
        btnProCocacola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProCocacolaActionPerformed(evt);
            }
        });

        btnProCocacolazero.setText("Coca Cola Zero");
        btnProCocacolazero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProCocacolazeroActionPerformed(evt);
            }
        });

        btnProFantanaranja.setText("Fanta Naranja");
        btnProFantanaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProFantanaranjaActionPerformed(evt);
            }
        });

        btnProMonster.setText("Monster");
        btnProMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProMonsterActionPerformed(evt);
            }
        });

        btnProRedbull.setText("Red Bull");
        btnProRedbull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProRedbullActionPerformed(evt);
            }
        });

        btnProNestea.setText("Nestea");
        btnProNestea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProNesteaActionPerformed(evt);
            }
        });

        lblFacturas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFacturas.setText("Facturas");
        lblFacturas.setToolTipText("");
        lblFacturas.setFocusable(false);
        lblFacturas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFacturas.setName(""); // NOI18N

        tFacturas.setModel(this.facturaTableModel);
        jScrollPane1.setViewportView(tFacturas);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotal.setText("Total: 0,0€");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnFacturasSum.setText("+");

        btnEliminarseleccion.setText("Eliminar Seleccion");

        btnFacturasRes.setText("-");

        btnAtras.setText("Atrás");

        lblNoHayCategorias.setForeground(new java.awt.Color(255, 10, 10));
        lblNoHayCategorias.setText("No hay categorías");

        lblNoHayProductos.setForeground(new java.awt.Color(255, 10, 10));
        lblNoHayProductos.setText("No hay productos");

        lblNoSeleccion.setForeground(new java.awt.Color(255, 10, 10));
        lblNoSeleccion.setText("No ha seleccionado nada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblProductos)
                                    .addComponent(lblCategorias))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(btnCatHamburguesas, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNoHayProductos)
                                            .addComponent(lblNoHayCategorias)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnProCocacolazero, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnProCocacola, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnProFantanaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnProRedbull, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnProMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnProNestea, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFacturas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNoSeleccion))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFacturasSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnFacturasRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnEliminarseleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategorias)
                    .addComponent(lblFacturas)
                    .addComponent(lblNoHayCategorias)
                    .addComponent(lblNoSeleccion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblProductos)
                                    .addComponent(lblNoHayProductos))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCatHamburguesas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProCocacola, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProFantanaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProRedbull, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProCocacolazero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProNestea, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnFacturasSum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFacturasRes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCatHamburguesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatHamburguesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatHamburguesasActionPerformed

    private void btnProCocacolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProCocacolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProCocacolaActionPerformed

    private void btnProCocacolazeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProCocacolazeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProCocacolazeroActionPerformed

    private void btnProFantanaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProFantanaranjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProFantanaranjaActionPerformed

    private void btnProMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProMonsterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProMonsterActionPerformed

    private void btnProRedbullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProRedbullActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProRedbullActionPerformed

    private void btnProNesteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProNesteaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProNesteaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCatHamburguesas;
    private javax.swing.JButton btnEliminarseleccion;
    private javax.swing.JButton btnFacturasRes;
    private javax.swing.JButton btnFacturasSum;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnProCocacola;
    private javax.swing.JButton btnProCocacolazero;
    private javax.swing.JButton btnProFantanaranja;
    private javax.swing.JButton btnProMonster;
    private javax.swing.JButton btnProNestea;
    private javax.swing.JButton btnProRedbull;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategorias;
    private javax.swing.JLabel lblFacturas;
    private javax.swing.JLabel lblNoHayCategorias;
    private javax.swing.JLabel lblNoHayProductos;
    private javax.swing.JLabel lblNoSeleccion;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tFacturas;
    // End of variables declaration//GEN-END:variables
}
