/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.pedidos;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AdoneyDAW
 */
public class PedidosProductosView extends javax.swing.JFrame {

    /**
     * Creates new form PedidosProductosView
     */
    
    private DefaultTableModel facturaTableModel;
    
    public PedidosProductosView(DefaultTableModel tableModel,String[] categoriasButtonNames) {
        this.facturaTableModel = tableModel;
        
        initComponents();
        
        //Modificando estilos
        this.panelCategorias.setLayout(new FlowLayout(NORMAL));
        this.panelCategorias.setPreferredSize(new Dimension(500, 100));
        this.panelProductos.setLayout(new FlowLayout(NORMAL));
        this.panelProductos.setPreferredSize(new Dimension(500, 100));
    }
    
    public void addProductosButtons(String[] nombreProductos) {
        for (String nombreProducot : nombreProductos) {
            JButton btnProducto = new JButton (nombreProducot);
            btnProducto.setPreferredSize(new Dimension(160, 40));
            
            this.panelProductos.add(btnProducto);
        }
    }
    
    public JButton getBtnAtras() {
        return this.btnAtras;
    }
    
    public JLabel getLblCategorias() {
        return this.lblCategorias;
    }
    
    public JLabel getLblProductos() {
        return this.lblProductos;
    }
    
    public JLabel getLblNoHayCategorias() {
        return this.lblNoHayCategorias;
    }
    
    public JLabel getLblNoHayProductos() {
        return this.lblNoHayProductos;
    }
    
    public JLabel getLblNoSeleccion() {
        return this.lblNoSeleccion;
    }
    
    public JLabel getLblNoGuardar() {
        
    }
    
    public JButton getBtnEliminarSeleccion() {
        return this.btnEliminarseleccion;
    }
    
    public JButton getBtnGuardar() {
        return this.btnGuardar;
    }
    
    public JScrollPane getScrollPane() {
        return this.scrollTableFacturas;
    } 
    
    public JTable getTable() {
        return this.tFacturas;
    }
    
    public JPanel getCategoriaPanel() {
        return this.panelCategorias;
    }
    
    public JPanel getProductoPanel() {
        return this.panelProductos;
    }
    
    public JButton[] getCategoriasButtons() {
        JButton[] categoriasButtons;
        
        Component[] componentes = this.panelCategorias.getComponents();
        
        categoriasButtons = new JButton[componentes.length];
        
        for (int a = 0; a<componentes.length; a++) {
            JButton botonActual = (JButton) componentes[a];
            
            categoriasButtons[a] = botonActual;
        }
        
        return categoriasButtons;
    }
    
    public JButton[] getProductosButtons() {
        JButton[] productosButtons;
        
        Component[] componentes = this.panelProductos.getComponents();
        
        productosButtons = new JButton[componentes.length];
        
        for (int a = 0; a<componentes.length; a++) {
            JButton botonActual = (JButton) componentes[a];
            
            productosButtons[a] = botonActual;
        }
        
        return productosButtons;
    }
    
    public JLabel getLblTotal() {
        return this.lblTotal;
    }
    
    public JButton getBtnMas() {
        return this.btnFacturasSum;
    }
    
    public JButton getBtnMenos() {
        return this.btnFacturasRes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCategorias = new javax.swing.JLabel();
        lblFacturas = new javax.swing.JLabel();
        scrollTableFacturas = new javax.swing.JScrollPane();
        tFacturas = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnFacturasSum = new javax.swing.JButton();
        btnEliminarseleccion = new javax.swing.JButton();
        btnFacturasRes = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblNoHayCategorias = new javax.swing.JLabel();
        lblNoSeleccion = new javax.swing.JLabel();
        panelCategorias = new javax.swing.JPanel();
        panelProductos = new javax.swing.JPanel();
        lblProductos = new javax.swing.JLabel();
        lblNoHayProductos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCategorias.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCategorias.setText("Categorías: ");
        lblCategorias.setToolTipText("");
        lblCategorias.setFocusable(false);
        lblCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCategorias.setName(""); // NOI18N

        lblFacturas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFacturas.setText("Facturas");
        lblFacturas.setToolTipText("");
        lblFacturas.setFocusable(false);
        lblFacturas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFacturas.setName(""); // NOI18N

        tFacturas.setModel(this.facturaTableModel);
        scrollTableFacturas.setViewportView(tFacturas);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotal.setText("Total: 0,0€");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnFacturasSum.setText("+");

        btnEliminarseleccion.setText("Eliminar Seleccion");

        btnFacturasRes.setText("-");

        btnAtras.setText("Atrás");

        lblNoHayCategorias.setForeground(new java.awt.Color(255, 10, 10));
        lblNoHayCategorias.setText("No hay categorías");

        lblNoSeleccion.setForeground(new java.awt.Color(255, 10, 10));
        lblNoSeleccion.setText("No ha seleccionado nada");

        panelCategorias.setAutoscrolls(true);
        panelCategorias.setPreferredSize(new java.awt.Dimension(463, 100));

        javax.swing.GroupLayout panelCategoriasLayout = new javax.swing.GroupLayout(panelCategorias);
        panelCategorias.setLayout(panelCategoriasLayout);
        panelCategoriasLayout.setHorizontalGroup(
            panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        panelCategoriasLayout.setVerticalGroup(
            panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );

        panelProductos.setAutoscrolls(true);
        panelProductos.setPreferredSize(new java.awt.Dimension(463, 100));

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        lblProductos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblProductos.setText("Productos: ");
        lblProductos.setToolTipText("");
        lblProductos.setFocusable(false);
        lblProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblProductos.setName(""); // NOI18N

        lblNoHayProductos.setForeground(new java.awt.Color(255, 10, 10));
        lblNoHayProductos.setText("No hay productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblCategorias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNoHayCategorias))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblProductos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNoHayProductos)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFacturas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNoSeleccion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFacturasSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnFacturasRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnEliminarseleccion, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                            .addComponent(scrollTableFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategorias)
                    .addComponent(lblFacturas)
                    .addComponent(lblNoHayCategorias)
                    .addComponent(lblNoSeleccion))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(scrollTableFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProductos)
                            .addComponent(lblNoHayProductos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnFacturasSum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFacturasRes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminarseleccion;
    private javax.swing.JButton btnFacturasRes;
    private javax.swing.JButton btnFacturasSum;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblCategorias;
    private javax.swing.JLabel lblFacturas;
    private javax.swing.JLabel lblNoHayCategorias;
    private javax.swing.JLabel lblNoHayProductos;
    private javax.swing.JLabel lblNoSeleccion;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelCategorias;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JScrollPane scrollTableFacturas;
    private javax.swing.JTable tFacturas;
    // End of variables declaration//GEN-END:variables
}
