
//@@@@@@@@@@@@@@@@ PROYECTO Brandom-Adoney


package view.administracion.gestion;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableModel;

/**
 * * González Olivares Brandon - Tejera Santana Adoney
 */
public class AdministracionCategoriasView extends javax.swing.JFrame {

    /**
     * Creates new form AdministracionCategoriasView
     */
    
    private final String[] categoriasTableColumns = {"ID", "Nombre"};
    private TableModel categoriasTableModel;
    
    public AdministracionCategoriasView(TableModel tableModel) {
        String[][] temporalCategoriasTableModel = {{"1", "Refrescos"}, {"2", "Bocatas"}, {"3", "Platos"}};
        
        this.categoriasTableModel = tableModel;
        
        initComponents();
    }
    
    public JTextField getTextFieldNewNombre() {
        return this.fieldCrearcategoria;
    }
    
    public JTextField getTextFieldEditNombre() {
        return this.fieldEditarcategoria;
    }
    
    public JButton getBtnAtras() {
        return this.btnAtras;
    }
    
    public JButton getBtnCrear() {
        return this.btnCrearcategoria;
    }
    
    public JButton getBtnGuardar() {
        return this.btnEditarcategoria;
    }
    
    public JButton getBtnEliminar() {
        return this.btnEliminarseleccion;
    }
    
    public JLabel getLblNewVacio() {
        return this.lblNewVacio;
    }
    
    public JLabel getLblEditVacio() {
        return this.lblEditVacio;
    }
    
    public JLabel getLblEditSeleccion() {
        return lblEditSeleccion;
    }
    
    public JScrollPane getScrollPane() {
        return this.ScrollCategorias;
    }
    
    public JTable getTable() {
        return this.tCategorias;
    }
    
    public JLabel getLblNewUnico() {
        return this.lblNewUnico;
    }
    
    public JLabel getLblEditUnico() {
        return this.lblEditUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCrearcategoria = new javax.swing.JLabel();
        fieldCrearcategoria = new javax.swing.JTextField();
        btnCrearcategoria = new javax.swing.JButton();
        lblEditarcategoria = new javax.swing.JLabel();
        fieldEditarcategoria = new javax.swing.JTextField();
        btnEditarcategoria = new javax.swing.JButton();
        lblCategorias = new javax.swing.JLabel();
        btnEliminarseleccion = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblNewVacio = new javax.swing.JLabel();
        lblEditVacio = new javax.swing.JLabel();
        lblEditSeleccion = new javax.swing.JLabel();
        ScrollCategorias = new javax.swing.JScrollPane();
        tCategorias = new javax.swing.JTable();
        lblNewUnico = new javax.swing.JLabel();
        lblEditUnico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCrearcategoria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblCrearcategoria.setText("Crear Categoría:");

        fieldCrearcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCrearcategoriaActionPerformed(evt);
            }
        });

        btnCrearcategoria.setText("Crear");

        lblEditarcategoria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblEditarcategoria.setText("Editar Categoría:");

        fieldEditarcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEditarcategoriaActionPerformed(evt);
            }
        });

        btnEditarcategoria.setText("Modificar");

        lblCategorias.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblCategorias.setText("Categorías:");

        btnEliminarseleccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnEliminarseleccion.setText("Eliminar Selección");

        btnAtras.setText("Atrás");

        lblNewVacio.setForeground(new java.awt.Color(255, 10, 10));
        lblNewVacio.setText("Nombre de categoría vacío");

        lblEditVacio.setForeground(new java.awt.Color(255, 10, 10));
        lblEditVacio.setText("Nombre de categoría vacío");

        lblEditSeleccion.setForeground(new java.awt.Color(255, 10, 10));
        lblEditSeleccion.setText("Debe seleccionar una categoría");

        tCategorias.setModel(this.categoriasTableModel);
        ScrollCategorias.setViewportView(tCategorias);

        lblNewUnico.setForeground(new java.awt.Color(255, 10, 10));
        lblNewUnico.setText("El nombre debe ser único");

        lblEditUnico.setForeground(new java.awt.Color(255, 10, 10));
        lblEditUnico.setText("El nombre debe ser único");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnEditarcategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldEditarcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEditarcategoria))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCrearcategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                .addComponent(fieldCrearcategoria)
                                .addComponent(lblCrearcategoria))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNewUnico)
                            .addComponent(lblNewVacio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEditUnico)
                            .addComponent(lblEditVacio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblEditSeleccion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategorias)
                    .addComponent(ScrollCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminarseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrearcategoria)
                    .addComponent(lblCategorias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldCrearcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCrearcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNewVacio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNewUnico)
                        .addGap(24, 24, 24)
                        .addComponent(lblEditarcategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldEditarcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditarcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEditVacio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEditUnico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEditSeleccion))
                    .addComponent(ScrollCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnEliminarseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCrearcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCrearcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCrearcategoriaActionPerformed

    private void fieldEditarcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEditarcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEditarcategoriaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollCategorias;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCrearcategoria;
    private javax.swing.JButton btnEditarcategoria;
    private javax.swing.JButton btnEliminarseleccion;
    private javax.swing.JTextField fieldCrearcategoria;
    private javax.swing.JTextField fieldEditarcategoria;
    private javax.swing.JLabel lblCategorias;
    private javax.swing.JLabel lblCrearcategoria;
    private javax.swing.JLabel lblEditSeleccion;
    private javax.swing.JLabel lblEditUnico;
    private javax.swing.JLabel lblEditVacio;
    private javax.swing.JLabel lblEditarcategoria;
    private javax.swing.JLabel lblNewUnico;
    private javax.swing.JLabel lblNewVacio;
    private javax.swing.JTable tCategorias;
    // End of variables declaration//GEN-END:variables
}
